### ISSUE TITLE
this.user is null on app.js

### ISSUE THREAD

**Issue by BertCatsburg** [delventhalz/transfer-chain-js#3]
Hello, 

Upon transferring a Tuna, I get a console message: 
```
TypeError: this.user is null
```
The message refers to app.js line 46. 
Where in app.js is the user set?

No transfers are done and nothing shows up on the Client below the "Accept Tuna" header.

**Comment by delventhalz** [comment]
User is set on changes to the "keySelect" dropdown. User can be set to null if you select "none" from the dropdown.

https://github.com/delventhalz/transfer-chain-js/blob/master/client/src/app.js#L68
