### ISSUE TITLE
Not able to see sawtooth-client-default while installing sawtooth for transfer-chain-js

### ISSUE THREAD

**Issue by aswinkumarrhex** [delventhalz/transfer-chain-js#4]
Hi trying to install the transfer-chain app for exploring sawtooth on ubuntu 16.
![image](https://user-images.githubusercontent.com/20457599/38291605-0e2fbdd0-37fe-11e8-93c4-ab5a3008227a.png)
this is a VM with only ssh option so any help will be greatly appreciated. 
Issue closely mirrors https://github.com/hyperledger/education/issues/26

**Comment by Enllave** [comment]
Hi aswinkumarrhex:

You are trying to exec a container (sawtooth-client-default) that does not appear in the .yaml file (docker-compose.yaml)

**Comment by delventhalz** [comment]
Perhaps you meant `transfer-shell`? `sawtooth-client-default` is a container core Sawtooth uses, but not this repo. The only containers here are the ones listed in the docker compose file:
https://github.com/delventhalz/transfer-chain-js/blob/master/docker-compose.yaml
